### ISSUE TITLE
apple tv的kodi不能播放

### ISSUE THREAD

**Issue by ws115** [0987363/douyutv-fix#1]
你好，最新版本的插件在apple tv4的kodi里不能播放，只能看到列表

**Comment by 0987363** [comment]
呃，哪个版本的osx，mbp的10.10.5上测试正常，kodi15.1

**Comment by ws115** [comment]
tvos 9.1 kodi 17.0

**Comment by 0987363** [comment]
官网最新release是15.2呢，或者16.0 b4

**Comment by ws115** [comment]
这里的
http://mirrors.kodi.tv/test-builds/darwin/tvos/

**Comment by 0987363** [comment]
因为没有tvos，所以在你发的连接里下载了osx的最新版本的，是16.0 beta5，播放正常

**Comment by ws115** [comment]
我就想弄到apple tv里看，也只能装这个版本

**Comment by 0987363** [comment]
我这没tvos，所以没法测。。你把kodi日志发来看看呢。 osx路径是/Users/xxxxx/Library/Logs/kodi.log

**Comment by ws115** [comment]
http://pan.baidu.com/s/1dEuAPuL

**Comment by 0987363** [comment]
貌似这是新版kodi的一个bug，部分平台已经修复了，tvos的可能还没修复，你用的具体哪个版本，换最新的nightly试试

**Comment by ws115** [comment]
我用的是最新的1月3日的版本

**Comment by 0987363** [comment]
问过了，最新的github nightly的是ok的，你只有多关注打包好的。或者自己编译。

**Comment by ws115** [comment]
你也可以买一台来测试下，目前测了所有tvos版本都不能放

**Comment by ws115** [comment]
Jan 13 18:24:42 Apple-TV Kodi[52770] <Warning>: Debug Print: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--

```
 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!

Error Type: <type 'exceptions.AttributeError'>

Error Contents: 'module' object has no attribute 'PLAYER_CORE_DVDPLAYER'

Traceback (most recent call last):

  File "/var/mobile/Containers/Data/Application/77E9FEB2-A921-4B53-B350-759D5B2B9777/Library/Caches/home/addons/douyu-kodi-fix/douyutv.py", line 79, in <module>

    player = xbmc.Player(xbmc.PLAYER_CORE_DVDPLAYER).play(videoUrl, item)

AttributeError: 'module' object has no attribute 'PLAYER_CORE_DVDPLAYER'

-->End of Python script error report<--
```

你好,    player = xbmc.Player(xbmc.PLAYER_CORE_DVDPLAYER).play(videoUrl, item)
这句话错了,能不能用别的播放器替代
