### ISSUE TITLE
Issue on douyutv.py line 68 data = api.loadRoom(roomId[0])  # helper.request("room/" + roomId[0])

### ISSUE THREAD

**Issue by ashtonfei** [0987363/douyutv-fix#5]
data 的返回的是一个空的List，而不是一个Dict，导致69,70出现错误。
 #68   data = api.loadRoom(roomId[0])  # helper.request("room/" + roomId[0]) 
 #69  rtmp_url = data["rtmp_url"]
 #70   rtmp_live = data["rtmp_live"]

**Comment by 0987363** [comment]
fixed it
