### ISSUE TITLE
你好，请问麻烦问下这个AUTH的加密规则是怎么找到了？

### ISSUE THREAD

**Issue by yugai** [0987363/douyutv-fix#6]
好像由于更新了API   auth加密规则也变了。 可以更新下加密规则吗？  或者提供下解密思路

**Comment by 0987363** [comment]
以前加密是放在app的java代码里的，所以能找到，现在丫写进so了，所以没辙了

**Comment by yugai** [comment]
丫的  我现在也在反编译 找他们的加密方式。
![qq 20161115135802](https://cloud.githubusercontent.com/assets/8723944/20294775/b5133920-ab3b-11e6-8558-b89a202aaddb.png)

**Comment by yugai** [comment]
请教下  有办法 能使用他们的so 文件吗？

**Comment by 0987363** [comment]
木有。。 他们加密方式放so里了， 我还发现斗鱼账号被封了。。。
