### ISSUE TITLE
安装依赖错误，需要更新源返回地址

### ISSUE THREAD

**Issue by Qeynos** [0987363/douyutv-fix#7]
安装显示无法满足xmbc python 3.0.0 依赖，并且不知道怎么解决

另外最近直播源失效了，douyu.py已经更新很多版本了，但直接更新会出错，我尝试了可以只更新最后的返回地址为
return "http://dyscdnali1.douyucdn.cn/live/{}.flv?uuid=".format(key)

**Comment by 0987363** [comment]
需要更新到新版kodi，python已升级到python3

更新新版docker，或者docker映射新的douyu.py就行了
-v /home/base/docker/data/douyu/douyu.py:/app/py/douyu.py

新的douyu.py，https://github.com/0987363/agent/blob/master/py/douyu.py

**Comment by Qeynos** [comment]
因为是在电视上用，装的libreelec，正式版还没有更新kodi到19，我是通过映射douyu.py并且修改地址暂时可以用
